### ISSUE TITLE
LaMetric not compatible with Nightscout Security Roles

### ISSUE THREAD

**Issue by hiltermann** [mlukasek/LaMetric_Nightscout_monitor#1]
We are very happy users of the LaMetric Nighscout app you've created! It prevents us from having to look for and pick up our phone all the time.

Currently Nightscout needs to be "readable by world" in order for the LaMetric app to work. In case I limit the access by settings AUTH_DEFAULT_ROLES variable in Heroku as denied and create an access roles and token for LaMetric I get the following error: _Bad Nightscout site, please configure the Nightscout monitor App with your site._

Would it be possible add support for a security token (as additional parameter) in LaMetric?

**Comment by mlukasek** [comment]
Token support added to the version 11, try to update please.
