### ISSUE TITLE
Now works with the Gluroo Nightscout-Compatible API

### ISSUE THREAD

**Issue by gjbadros** [mlukasek/LaMetric_Nightscout_monitor#2]
Just a note that we've fixed a bug in our nightscout-compatible backend of https://gluroo.com to make this work. Thanks for the great project, Martin, and thanks to our users for the bug report.  Users should be sure *not* to enter the https:// prefix on their site and only enter, e.g., 

xyzk.ns.gluroo.com

Thanks!

**Comment by mlukasek** [comment]
Great, thank you!
